runtime: python310

handlers:
- url: /old_website
  static_dir: old_website

- url: /Rahul_Garg_files
  static_dir: Rahul_Garg_files

- url: /(.*\.(|PNG|gif|png|jpg|ico|js|css|pdf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|pdf))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  static_files: index.html
  upload: index.html
